export const data = [
  {
    id: "1",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "2",
    level: "4",
    name: "Mohamed Ahmed",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "3",
    level: "4",
    name: "Maged Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "4",
    level: "4",
    name: "Mohamed Ali",
    email: "student@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "5",
    level: "4",
    name: "Mohamed eid",
    email: "mohamed_student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "6",
    level: "4",
    name: "Mohamed sayed",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "7",
    level: "4",
    name: "Alaa Rageh",
    email: "mohamed_student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "8",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "9",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "10",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
];
export const listOfProf = [
  {
    id: "1",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "2",
    level: "4",
    name: "Mohamed Ahmed",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "3",
    level: "4",
    name: "Maged Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "4",
    level: "4",
    name: "Mohamed Ali",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "5",
    level: "4",
    name: "Mohamed eid",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "6",
    level: "4",
    name: "Mohamed sayed",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "7",
    level: "4",
    name: "Alaa Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "8",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "9",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
  {
    id: "10",
    level: "4",
    name: "Mohamed Rageh",
    email: "mohamed_professor@gmail.com",
    role: "professor",
    code: "65387",
  },
];
export const listOfStd = [
  {
    id: "1",
    level: "4",
    name: "Mohamed Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "2",
    level: "4",
    name: "Mohamed Ahmed",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "3",
    level: "4",
    name: "Maged Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "4",
    level: "4",
    name: "Mohamed Ali",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "5",
    level: "4",
    name: "Mohamed eid",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "6",
    level: "4",
    name: "Mohamed sayed",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "7",
    level: "4",
    name: "Alaa Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "8",
    level: "4",
    name: "Mohamed Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "9",
    level: "4",
    name: "Mohamed Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
  {
    id: "10",
    level: "4",
    name: "Mohamed Rageh",
    email: "student@gmail.com",
    role: "student",
    code: "65387",
  },
];
