export const courses = [

  {
    id:"1",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"2",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"3",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"4",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"5",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"6",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"7",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"8",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  {
    id:"9",
    level: "4",
    name: "Software Engineer",
    description: "Software Engineer",
    professor: "Mohamed Ali",
    image: "/images/hero4.jpg",
  },
  
];
